from elements.main_page_elements import MainPageElements
from elements.news_page_elements import NewsPageElements
from elements.header_elements import HeaderElements
from elements.news_detailed_page_elements import NewsDetailedPageElements
from elements.brand_page_elements import BrandPageElements
from elements.brand_detailed_page_elements import BrandDetailedPageElements
from elements.sales_page_elements import SalesPageElements
from elements.sales_detailed_page_elements import SalesDetailedPageElements
